---
title: "Curriculum Vitae"
---

[Download CV](Files/Cv_Pdf.pdf).			

# EDUCATION

*University of Luxembourg*, Cert. in Sust. Dvlp and Soc. Innov. \hfill 09/2017-Present

*FEA, University of São Paulo*, Erasmus Mundus \hfill 07/2016-01/2017

*University of Namur*, MBA, Distinction \hfill 09/2015-06/2018  

> **Thesis** | "Towards Green Companies: A Panel Data Study of The Environmental and Financial Performance Nexus", available on my [GitHub](https://github.com/pkinif/Thesis) account.

*University of Namur*, BBA \hfill 09/2012-09/2015

*CE Saint-Joseph of Chimay*, High School, General Studies \hfill 09/2007-06/2012

# EXPERIENCE

*Assistant, Sustainability Practice at [IMS Luxembourg](http://imslux.lu/)* \hfill 09/2017-03/2018

Luxemburgish network that accompanies organisations in their commitment to CSR by enhancing dialogue with their stakeholders.

- Results analysis of a CSR survey for presentation during the [Luxembourg Sustainability Forum (i.e. LSF) 2017](https://www.youtube.com/watch?v=GIjwK_j_HyY) and later publication. 

- Help for the organization of the LSF2017 + media follow-up 

- Organization of a workshop in the context of the *Food* pillar of the [*"Third Industrial Revolution"*](http://www.troisiemerevolutionindustrielle.lu/)

- Measurement of the company's carbon footprint

- Research and writing assistance for the publication of the magazine *"Sustainability MAG"*

*Credit Risk Data Analyst Intern at [BIL Luxembourg](https://www.bil.com/fr/Pages/index.aspx)* \hfill 01/2017-06/2017

The oldest private banking group in the Grand Duchy and among the country’s top three banks. 

- Validatation and ensure consistency of the credit risk databases used by the different departments of the bank.

- Developement of an application to automatize the data validation process.

*Campus Consultant at [4uCampus](https://www.4ucampus.be/fr/)* \hfill 09/2015-03/2016

Company which offers reductions on newspapers, magazines, computers, softwares and printers to students and academic staff.

- Sales of subscriptions of press titles to students and academic staff

- Give speeches to academic audience to promote company's products 

- Prospection 

*Consulting Project at [Lunch Garden](https://www.lunchgarden.be/fr?gclid=EAIaIQobChMIx6rm_s282wIVhJ3VCh1brww1EAAYASAAEgK7A_D_BwE)* \hfill 09/2015-01/2016

Belgian fast food chain of more than 70 restaurants. 

- Team project to improve the employer branding of the company

*Barman and Server at [Les Caves à Bières](https://www.google.com/url?sa=t&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiynrj6rb3bAhUsJ8AKHeloA60QFgguMAA&url=https%3A%2F%2Ffr-fr.facebook.com%2Fpages%2FLes-Caves-%25C3%2580-Bi%25C3%25A8res%2F186535764722243&usg=AOvVaw3QgJ8qNQfPsKg4xsqVIf3t), the [Piano bar](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi-9KvXrb3bAhVKI8AKHQLxBiMQFgguMAA&url=https%3A%2F%2Ffr-fr.facebook.com%2Flepianobarnamur%2F&usg=AOvVaw2czC_1tmXbWBVyH_t6Q9hW) and the [Arsenal](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwi3gJ2Vrr3bAhWRasAKHXc8DtYQFgg-MAE&url=https%3A%2F%2Fwww.unamur.be%2Fservices%2Fsocial%2Farsenal&usg=AOvVaw1EWoWte0qHjoIsPppcGMhT)* Namur \hfill 09/2012-12-2015

- Financing my studies

- Learning process of delicious cocktail recipes

- Reinforcement of my customer service


# LANGUAGES

## Programming

> **Proficient**: R, Rmarkdown, Reproducible Research, \LaTeX\, GitHub, Zotero, VBA, Pack Office

> **Familiar**:   SQL, SAP BO, Stata, SPSS, Oxmétrics, Html, Jekyll

## Written & Spoken

> **French**:     Native Fluency

> **English**:    Professional working proficiency (i.e. C1 level)

> **Dutch**:      Limited working proficiency (i.e. B1 level)

> **Spanish**:    Elementary proficiency (i.e. A1 level)

# CERTIFICATION

> Data Analyst with R Certification, DataCamp, June 2018
